services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: university
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: